# Generated by Django 4.2 on 2023-04-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'recruiters',
                'ordering': ['first_name', 'last_name'],
            },
            bases=('workers.worker',),
        ),
    ]
