# Generated by Django 4.2 on 2023-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='linkedin_id',
            field=models.CharField(max_length=50),
        ),
    ]
