# Generated by Django 4.2 on 2023-04-20 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_comment='Primary key for all the models', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_comment='Object creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_comment='Object updating date')),
                ('name', models.CharField(max_length=30)),
                ('company_url', models.URLField(max_length=400)),
                ('linkedin_id', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('company_roles', models.ManyToManyField(to='companies.jobtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
