# Generated by Django 4.2 on 2023-04-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
    ]
