# Generated by Django 4.2 on 2023-04-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadhuntingFirm',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
            bases=('companies.company',),
        ),
    ]
