# Generated by Django 4.2 on 2023-04-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_softwarecompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarecompany',
            options={'ordering': ['name'], 'verbose_name_plural': 'Software companies'},
        ),
    ]
