# Generated by Django 4.2 on 2023-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_softwarecompany_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecompany',
            name='industry',
            field=models.CharField(choices=[('Software', 'Software'), ('Education', 'Education'), ('Energy', 'Energy'), ('Manufacturing', 'Manufacturing'), ('Finance', 'Finance'), ('Social Media', 'Social Media'), ('Media', 'Media'), ('Healthcare', 'Healthcare')], default='Software', max_length=20),
        ),
    ]
