# Generated by Django 4.2 on 2023-04-22 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0003_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(db_comment='Primary key for all the models', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_comment='Object creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_comment='Object updating date')),
                ('channel', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], default='LinkedIn', max_length=20)),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], default='English', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('text', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='workers.worker')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
