# Generated by Django 4.2 on 2023-04-23 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobdescription_software_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(db_comment='Primary key for all the models', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_comment='Object creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_comment='Object updating date')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'questions',
                'ordering': ['text'],
            },
        ),
    ]
