# Generated by Django 4.2 on 2023-04-23 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(db_comment='Primary key for all the models', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_comment='Object creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_comment='Object updating date')),
                ('channel', models.IntegerField(choices=[(0, 'Phone'), (1, 'Email'), (2, 'Meet'), (3, 'Test')], default='Zero')),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('questions', models.ManyToManyField(to='jobs.question')),
                ('selection_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.selectionprocess')),
            ],
            options={
                'verbose_name_plural': 'stages',
                'ordering': ['event_date'],
            },
        ),
    ]
