# Generated by Django 4.2 on 2023-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_selectionprocess_headhunting_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
