# Generated by Django 4.2 on 2023-04-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_linkedin_id'),
        ('jobs', '0008_alter_jobdescription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
    ]
